- hosts: laptop
#  remote_user: root
#  become: yes
#  become_method: sudo
#  become_user: root
  vars:
    group: atomic
    # The Red Hat supplied RHEL 7 Atomic Host image
    disk_image: "{{ atomic_disk_image }}"
  roles:
  - kvm_hypervisor

- hosts: atomic
  become: yes
  become_method: sudo
  become_user: root
  remote_user: cloud-user
  vars_files:
    - passes.yml
  vars:
    # for the demo application
    # this is built using s2i from https://github.com/jduncan-rva/php-demo-app
    app_image: jeduncan/php-demo-app
    # set this to true and gluster containers are deployed on each host and available for use
    use_gluster_direct_mount: true
    # set this to true and supply and nfs_server value and an NFS Persistent Volume and Persistent Volume Claim is created for use
    use_nfs_pv: true
    nfs_server: 192.168.122.1
    nfs_volume: /var/registry-data
  roles:
  - common
  - atomic
  - atomic-demo
